# Generated by Django 3.2.19 on 2023-07-06 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='engine',
            field=models.CharField(default='4-cylinder', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='fuel',
            field=models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='gasoline', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(default='2000'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='trade_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
